// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';
import {main} from '../models';

export function AddActivityToReport(arg1:number,arg2:number,arg3:string,arg4:string):Promise<db.ReportItem>;

export function AddEmploymentType(arg1:string):Promise<void>;

export function AddManualActivity(arg1:string,arg2:string,arg3:string):Promise<db.Activity>;

export function AddPositionType(arg1:string):Promise<void>;

export function AddProjectCategory(arg1:string):Promise<void>;

export function AddReportItem(arg1:number,arg2:string,arg3:string,arg4:string,arg5:any,arg6:string):Promise<db.ReportItem>;

export function AuthGmailAccount(arg1:string):Promise<string>;

export function CheckGmailAuth(arg1:string):Promise<main.StatusResult>;

export function CheckGogCLI():Promise<main.StatusResult>;

export function DeleteAttendanceRecord(arg1:number):Promise<void>;

export function DeleteClient(arg1:number):Promise<void>;

export function DeleteEmploymentType(arg1:string):Promise<void>;

export function DeleteMemberAssignment(arg1:number):Promise<void>;

export function DeletePositionType(arg1:string):Promise<void>;

export function DeleteProjectCategory(arg1:number):Promise<void>;

export function DeleteReportItem(arg1:number):Promise<void>;

export function DeleteSIProject(arg1:number):Promise<void>;

export function DeleteSIProjectMember(arg1:number):Promise<void>;

export function DeleteTeamMember(arg1:number):Promise<void>;

export function ExportWeeklyReport(arg1:number):Promise<string>;

export function GetAttendanceSummary(arg1:string,arg2:string):Promise<Array<db.AttendanceSummary>>;

export function GetAttendanceTypes():Promise<Array<string>>;

export function GetClientStatuses():Promise<Array<string>>;

export function GetCurrentUser():Promise<db.User>;

export function GetCurrentWeek():Promise<main.WeekInfo>;

export function GetDataDir():Promise<string>;

export function GetEmploymentTypes():Promise<Array<string>>;

export function GetExcelTemplate():Promise<db.ExcelTemplate>;

export function GetIntegrations():Promise<Array<db.Integration>>;

export function GetOrCreateWeeklyReport(arg1:string,arg2:string):Promise<db.WeeklyReport>;

export function GetPositionTypes():Promise<Array<string>>;

export function GetProjectCategories():Promise<Array<db.ProjectCategory>>;

export function GetReportItems(arg1:number):Promise<Array<db.ReportItem>>;

export function GetSIPhases():Promise<Array<string>>;

export function GetSIProjectStatuses():Promise<Array<string>>;

export function GetSIProjectTypes():Promise<Array<string>>;

export function GetSIProjectView(arg1:number,arg2:string,arg3:string):Promise<db.SIProjectView>;

export function GetSIRoles():Promise<Array<string>>;

export function GetSIWeeklySnapshot(arg1:string,arg2:string):Promise<db.SIWeeklySnapshot>;

export function GetUtilizationByDate(arg1:string):Promise<Array<db.UtilizationMemberRow>>;

export function GetWeekActivities(arg1:string,arg2:string):Promise<Array<main.ActivityWithSource>>;

export function GetWeekByOffset(arg1:number):Promise<main.WeekInfo>;

export function Greet(arg1:string):Promise<string>;

export function ListAttendanceRecords(arg1:number,arg2:string,arg3:string):Promise<Array<db.AttendanceRecord>>;

export function ListClients(arg1:string,arg2:boolean):Promise<Array<db.Client>>;

export function ListMemberAssignments(arg1:string,arg2:string):Promise<Array<db.MemberAssignment>>;

export function ListSIProjects():Promise<Array<db.ProjectWithClient>>;

export function ListTeamMembers():Promise<Array<db.TeamMember>>;

export function ListWeeklyReports():Promise<Array<db.WeeklyReport>>;

export function PopulateReportFromProjects(arg1:number,arg2:string,arg3:string):Promise<number>;

export function PopulateReportFromTeamData(arg1:number):Promise<number>;

export function PreprocessReportItemsWithAI(arg1:number):Promise<main.SyncResult>;

export function SaveAttendanceRecord(arg1:db.AttendanceRecord):Promise<db.AttendanceRecord>;

export function SaveClient(arg1:db.Client):Promise<db.Client>;

export function SaveIntegration(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SaveMemberAssignment(arg1:db.MemberAssignment):Promise<db.MemberAssignment>;

export function SaveSIProject(arg1:db.Project):Promise<db.Project>;

export function SaveSIProjectDetail(arg1:db.SIProjectDetail):Promise<db.SIProjectDetail>;

export function SaveSIProjectMember(arg1:db.SIProjectMember):Promise<db.SIProjectMember>;

export function SaveSIWeeklyReport(arg1:db.SIWeeklyReport):Promise<db.SIWeeklyReport>;

export function SaveTeamMember(arg1:db.TeamMember):Promise<db.TeamMember>;

export function SetupGogCredentials():Promise<string>;

export function SyncAll(arg1:string,arg2:string):Promise<Array<main.SyncResult>>;

export function SyncGmail(arg1:string,arg2:string):Promise<main.SyncResult>;

export function SyncGoogleCalendar(arg1:string,arg2:string):Promise<main.SyncResult>;

export function UpdateReportItem(arg1:db.ReportItem):Promise<void>;

export function UpdateSIProjectStatus(arg1:number,arg2:string):Promise<void>;

export function UpdateUser(arg1:string,arg2:string):Promise<void>;

export function UploadExcelTemplate():Promise<string>;
