// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddActivityToReport(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddActivityToReport'](arg1, arg2, arg3, arg4);
}

export function AddEmploymentType(arg1) {
  return window['go']['main']['App']['AddEmploymentType'](arg1);
}

export function AddManualActivity(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddManualActivity'](arg1, arg2, arg3);
}

export function AddPositionType(arg1) {
  return window['go']['main']['App']['AddPositionType'](arg1);
}

export function AddProjectCategory(arg1) {
  return window['go']['main']['App']['AddProjectCategory'](arg1);
}

export function AddReportItem(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['AddReportItem'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function AddSIPhase(arg1) {
  return window['go']['main']['App']['AddSIPhase'](arg1);
}

export function AddSIProjectType(arg1) {
  return window['go']['main']['App']['AddSIProjectType'](arg1);
}

export function AutoMapLinearMembers() {
  return window['go']['main']['App']['AutoMapLinearMembers']();
}

export function CheckClaudeCLI() {
  return window['go']['main']['App']['CheckClaudeCLI']();
}

export function CheckGWSAuth() {
  return window['go']['main']['App']['CheckGWSAuth']();
}

export function CheckGWSCLI() {
  return window['go']['main']['App']['CheckGWSCLI']();
}

export function ClaudeChat(arg1, arg2) {
  return window['go']['main']['App']['ClaudeChat'](arg1, arg2);
}

export function ClaudeChatWithSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['ClaudeChatWithSession'](arg1, arg2, arg3);
}

export function DeleteAttendanceRecord(arg1) {
  return window['go']['main']['App']['DeleteAttendanceRecord'](arg1);
}

export function DeleteClient(arg1) {
  return window['go']['main']['App']['DeleteClient'](arg1);
}

export function DeleteEmploymentType(arg1) {
  return window['go']['main']['App']['DeleteEmploymentType'](arg1);
}

export function DeleteIssue(arg1) {
  return window['go']['main']['App']['DeleteIssue'](arg1);
}

export function DeleteMemberAssignment(arg1) {
  return window['go']['main']['App']['DeleteMemberAssignment'](arg1);
}

export function DeletePositionType(arg1) {
  return window['go']['main']['App']['DeletePositionType'](arg1);
}

export function DeleteProjectCategory(arg1) {
  return window['go']['main']['App']['DeleteProjectCategory'](arg1);
}

export function DeleteReportItem(arg1) {
  return window['go']['main']['App']['DeleteReportItem'](arg1);
}

export function DeleteSIPhase(arg1) {
  return window['go']['main']['App']['DeleteSIPhase'](arg1);
}

export function DeleteSIProject(arg1) {
  return window['go']['main']['App']['DeleteSIProject'](arg1);
}

export function DeleteSIProjectMember(arg1) {
  return window['go']['main']['App']['DeleteSIProjectMember'](arg1);
}

export function DeleteSIProjectType(arg1) {
  return window['go']['main']['App']['DeleteSIProjectType'](arg1);
}

export function DeleteTeamMember(arg1) {
  return window['go']['main']['App']['DeleteTeamMember'](arg1);
}

export function ExportWeeklyReport(arg1) {
  return window['go']['main']['App']['ExportWeeklyReport'](arg1);
}

export function GetAttendanceSummary(arg1, arg2) {
  return window['go']['main']['App']['GetAttendanceSummary'](arg1, arg2);
}

export function GetAttendanceTypes() {
  return window['go']['main']['App']['GetAttendanceTypes']();
}

export function GetCalendars() {
  return window['go']['main']['App']['GetCalendars']();
}

export function GetClientStatuses() {
  return window['go']['main']['App']['GetClientStatuses']();
}

export function GetCurrentUser() {
  return window['go']['main']['App']['GetCurrentUser']();
}

export function GetCurrentWeek() {
  return window['go']['main']['App']['GetCurrentWeek']();
}

export function GetDataDir() {
  return window['go']['main']['App']['GetDataDir']();
}

export function GetEmploymentTypes() {
  return window['go']['main']['App']['GetEmploymentTypes']();
}

export function GetExcelTemplate() {
  return window['go']['main']['App']['GetExcelTemplate']();
}

export function GetExcelTemplateForType(arg1) {
  return window['go']['main']['App']['GetExcelTemplateForType'](arg1);
}

export function GetIntegrations() {
  return window['go']['main']['App']['GetIntegrations']();
}

export function GetLinearDashboard() {
  return window['go']['main']['App']['GetLinearDashboard']();
}

export function GetLinearTeamMembers() {
  return window['go']['main']['App']['GetLinearTeamMembers']();
}

export function GetLinearTeamStates() {
  return window['go']['main']['App']['GetLinearTeamStates']();
}

export function GetOrCreateWeeklyReport(arg1, arg2) {
  return window['go']['main']['App']['GetOrCreateWeeklyReport'](arg1, arg2);
}

export function GetPositionTypes() {
  return window['go']['main']['App']['GetPositionTypes']();
}

export function GetProjectCategories() {
  return window['go']['main']['App']['GetProjectCategories']();
}

export function GetReportItems(arg1) {
  return window['go']['main']['App']['GetReportItems'](arg1);
}

export function GetSIPhases() {
  return window['go']['main']['App']['GetSIPhases']();
}

export function GetSIProjectTypes() {
  return window['go']['main']['App']['GetSIProjectTypes']();
}

export function GetSIProjectView(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetSIProjectView'](arg1, arg2, arg3);
}

export function GetSIRoles() {
  return window['go']['main']['App']['GetSIRoles']();
}

export function GetSIWeeklySnapshot(arg1, arg2) {
  return window['go']['main']['App']['GetSIWeeklySnapshot'](arg1, arg2);
}

export function GetTeamProfile() {
  return window['go']['main']['App']['GetTeamProfile']();
}

export function GetUtilizationByDate(arg1) {
  return window['go']['main']['App']['GetUtilizationByDate'](arg1);
}

export function GetWeekActivities(arg1, arg2) {
  return window['go']['main']['App']['GetWeekActivities'](arg1, arg2);
}

export function GetWeekByOffset(arg1) {
  return window['go']['main']['App']['GetWeekByOffset'](arg1);
}

export function GetWeeklyReport(arg1) {
  return window['go']['main']['App']['GetWeeklyReport'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListAttendanceRecords(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListAttendanceRecords'](arg1, arg2, arg3);
}

export function ListClients(arg1, arg2) {
  return window['go']['main']['App']['ListClients'](arg1, arg2);
}

export function ListIssues(arg1) {
  return window['go']['main']['App']['ListIssues'](arg1);
}

export function ListMemberAssignments(arg1, arg2) {
  return window['go']['main']['App']['ListMemberAssignments'](arg1, arg2);
}

export function ListRetrospectives() {
  return window['go']['main']['App']['ListRetrospectives']();
}

export function ListSIProjects() {
  return window['go']['main']['App']['ListSIProjects']();
}

export function ListTeamMembers() {
  return window['go']['main']['App']['ListTeamMembers']();
}

export function ListWeeklyReports() {
  return window['go']['main']['App']['ListWeeklyReports']();
}

export function OpenFile(arg1) {
  return window['go']['main']['App']['OpenFile'](arg1);
}

export function PopulateReportFromProjects(arg1, arg2, arg3) {
  return window['go']['main']['App']['PopulateReportFromProjects'](arg1, arg2, arg3);
}

export function PopulateReportFromTeamData(arg1) {
  return window['go']['main']['App']['PopulateReportFromTeamData'](arg1);
}

export function PreprocessReportItemsWithAI(arg1) {
  return window['go']['main']['App']['PreprocessReportItemsWithAI'](arg1);
}

export function RefineMarkdownWithAI(arg1) {
  return window['go']['main']['App']['RefineMarkdownWithAI'](arg1);
}

export function SaveAttendanceRecord(arg1) {
  return window['go']['main']['App']['SaveAttendanceRecord'](arg1);
}

export function SaveClient(arg1) {
  return window['go']['main']['App']['SaveClient'](arg1);
}

export function SaveIntegration(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveIntegration'](arg1, arg2, arg3);
}

export function SaveIssue(arg1) {
  return window['go']['main']['App']['SaveIssue'](arg1);
}

export function SaveMemberAssignment(arg1) {
  return window['go']['main']['App']['SaveMemberAssignment'](arg1);
}

export function SaveRetrospective(arg1) {
  return window['go']['main']['App']['SaveRetrospective'](arg1);
}

export function SaveSIProject(arg1) {
  return window['go']['main']['App']['SaveSIProject'](arg1);
}

export function SaveSIProjectDetail(arg1) {
  return window['go']['main']['App']['SaveSIProjectDetail'](arg1);
}

export function SaveSIProjectMember(arg1) {
  return window['go']['main']['App']['SaveSIProjectMember'](arg1);
}

export function SaveSIWeeklyReport(arg1) {
  return window['go']['main']['App']['SaveSIWeeklyReport'](arg1);
}

export function SaveTeamMember(arg1) {
  return window['go']['main']['App']['SaveTeamMember'](arg1);
}

export function ScanClaudeSkills() {
  return window['go']['main']['App']['ScanClaudeSkills']();
}

export function SetupGWSAuth() {
  return window['go']['main']['App']['SetupGWSAuth']();
}

export function SetupTeamProfile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetupTeamProfile'](arg1, arg2, arg3, arg4);
}

export function SyncAll(arg1, arg2) {
  return window['go']['main']['App']['SyncAll'](arg1, arg2);
}

export function SyncGmail(arg1, arg2) {
  return window['go']['main']['App']['SyncGmail'](arg1, arg2);
}

export function SyncGoogleCalendar(arg1, arg2) {
  return window['go']['main']['App']['SyncGoogleCalendar'](arg1, arg2);
}

export function UpdateLinearIssue(arg1, arg2) {
  return window['go']['main']['App']['UpdateLinearIssue'](arg1, arg2);
}

export function UpdateLinearIssueState(arg1, arg2) {
  return window['go']['main']['App']['UpdateLinearIssueState'](arg1, arg2);
}

export function UpdateReportItem(arg1) {
  return window['go']['main']['App']['UpdateReportItem'](arg1);
}

export function UpdateSIProjectStatus(arg1, arg2) {
  return window['go']['main']['App']['UpdateSIProjectStatus'](arg1, arg2);
}

export function UpdateTeamProfile(arg1) {
  return window['go']['main']['App']['UpdateTeamProfile'](arg1);
}

export function UpdateUser(arg1, arg2) {
  return window['go']['main']['App']['UpdateUser'](arg1, arg2);
}

export function UploadExcelTemplate() {
  return window['go']['main']['App']['UploadExcelTemplate']();
}

export function UploadExcelTemplateForType(arg1) {
  return window['go']['main']['App']['UploadExcelTemplateForType'](arg1);
}
