// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {db} from '../models';
import {main} from '../models';
import {integrations} from '../models';

export function AcceptInsightActivity(arg1:number,arg2:number,arg3:string,arg4:string,arg5:string):Promise<db.ReportItem>;

export function AcceptInsightDraft(arg1:number,arg2:db.ReportInsightDraft,arg3:string):Promise<Array<db.ReportItem>>;

export function AddActivityToReport(arg1:number,arg2:number,arg3:string,arg4:string):Promise<db.ReportItem>;

export function AddEmploymentType(arg1:string):Promise<void>;

export function AddManualActivity(arg1:string,arg2:string,arg3:string):Promise<db.Activity>;

export function AddPersonalAIManualUsage(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number,arg6:number):Promise<void>;

export function AddPositionType(arg1:string):Promise<void>;

export function AddProjectCategory(arg1:string):Promise<void>;

export function AddReportItem(arg1:number,arg2:string,arg3:string,arg4:string,arg5:any,arg6:string):Promise<db.ReportItem>;

export function AddSIPhase(arg1:string):Promise<void>;

export function AddSIProjectType(arg1:string):Promise<void>;

export function AutoMapLinearMembers():Promise<number>;

export function CheckClaudeCLI():Promise<Record<string, any>>;

export function CheckGWSAuth():Promise<main.StatusResult>;

export function CheckGWSCLI():Promise<main.StatusResult>;

export function ClaudeChat(arg1:string,arg2:string):Promise<string>;

export function ClaudeChatWithSession(arg1:string,arg2:string,arg3:string):Promise<main.ClaudeChatResult>;

export function CollectPersonalAIUsage(arg1:string):Promise<db.PersonalAICollectorResponse>;

export function DeleteAIBillingPlan(arg1:number):Promise<void>;

export function DeleteAIModel(arg1:number):Promise<void>;

export function DeleteAIProvider(arg1:number):Promise<void>;

export function DeleteAttendanceRecord(arg1:number):Promise<void>;

export function DeleteClient(arg1:number):Promise<void>;

export function DeleteEmploymentType(arg1:string):Promise<void>;

export function DeleteIssue(arg1:number):Promise<void>;

export function DeleteMemberAssignment(arg1:number):Promise<void>;

export function DeletePositionType(arg1:string):Promise<void>;

export function DeleteProjectCategory(arg1:number):Promise<void>;

export function DeleteReportItem(arg1:number):Promise<void>;

export function DeleteSIPhase(arg1:string):Promise<void>;

export function DeleteSIProject(arg1:number):Promise<void>;

export function DeleteSIProjectMember(arg1:number):Promise<void>;

export function DeleteSIProjectType(arg1:string):Promise<void>;

export function DeleteTeamMember(arg1:number):Promise<void>;

export function ExportWeeklyReport(arg1:number):Promise<string>;

export function GetAIUsageDashboard(arg1:string):Promise<db.AIUsageDashboard>;

export function GetAttendanceSummary(arg1:string,arg2:string):Promise<Array<db.AttendanceSummary>>;

export function GetAttendanceTypes():Promise<Array<string>>;

export function GetCalendars():Promise<Array<integrations.Calendar>>;

export function GetClientStatuses():Promise<Array<string>>;

export function GetCurrentUser():Promise<db.User>;

export function GetCurrentWeek():Promise<main.WeekInfo>;

export function GetDataDir():Promise<string>;

export function GetEmploymentTypes():Promise<Array<string>>;

export function GetExcelTemplate():Promise<db.ExcelTemplate>;

export function GetExcelTemplateForType(arg1:string):Promise<db.ExcelTemplate>;

export function GetIntegrations():Promise<Array<db.Integration>>;

export function GetLinearDashboard():Promise<main.LinearDashboardData>;

export function GetLinearTeamLabels():Promise<Array<main.LinearIssueLabel>>;

export function GetLinearTeamMembers():Promise<Array<main.LinearTeamMember>>;

export function GetLinearTeamStates():Promise<Array<main.LinearWorkflowState>>;

export function GetMyAttendanceSummary(arg1:string,arg2:string):Promise<db.MyAttendanceSummary>;

export function GetMyLinearIssues():Promise<Array<main.LinearIssue>>;

export function GetOrCreateWeeklyReport(arg1:string,arg2:string):Promise<db.WeeklyReport>;

export function GetPersonalAIAutoCollect():Promise<db.PersonalAIAutoCollectConfig>;

export function GetPersonalAIUsageCollectionStatus():Promise<db.PersonalAICollectStatus>;

export function GetPersonalAIUsageDashboard(arg1:string):Promise<db.PersonalAIUsageDashboard>;

export function GetPersonalAIUsageHistory(arg1:string,arg2:number):Promise<Array<db.AIUsageHistoryEvent>>;

export function GetPositionTypes():Promise<Array<string>>;

export function GetProjectCategories():Promise<Array<db.ProjectCategory>>;

export function GetReportInsights(arg1:number):Promise<db.ReportInsights>;

export function GetReportItems(arg1:number):Promise<Array<db.ReportItem>>;

export function GetSIPhases():Promise<Array<string>>;

export function GetSIProjectTypes():Promise<Array<string>>;

export function GetSIProjectView(arg1:number,arg2:string,arg3:string):Promise<db.SIProjectView>;

export function GetSIRoles():Promise<Array<string>>;

export function GetSIWeeklySnapshot(arg1:string,arg2:string):Promise<db.SIWeeklySnapshot>;

export function GetTeamProfile():Promise<db.TeamProfile>;

export function GetUtilizationByDate(arg1:string):Promise<Array<db.UtilizationMemberRow>>;

export function GetVaultFile(arg1:string):Promise<db.VaultFile>;

export function GetVaultStructure(arg1:any):Promise<Array<db.VaultItem>>;

export function GetWeekActivities(arg1:string,arg2:string):Promise<Array<main.ActivityWithSource>>;

export function GetWeekByOffset(arg1:number):Promise<main.WeekInfo>;

export function GetWeeklyReport(arg1:number):Promise<db.WeeklyReport>;

export function Greet(arg1:string):Promise<string>;

export function IgnoreInsightActivity(arg1:number,arg2:number):Promise<void>;

export function IngestKnowledgeBatch(arg1:string,arg2:Array<string>,arg3:string,arg4:string):Promise<Array<db.IngestResult>>;

export function IngestKnowledgeSource(arg1:string,arg2:string,arg3:string,arg4:string):Promise<db.IngestResult>;

export function ListAIBillingPlans():Promise<Array<db.AIBillingPlan>>;

export function ListAIModels():Promise<Array<db.AIModel>>;

export function ListAIProviders():Promise<Array<db.AIProvider>>;

export function ListActivitiesByDateRange(arg1:string,arg2:string):Promise<Array<db.Activity>>;

export function ListAttendanceRecords(arg1:number,arg2:string,arg3:string):Promise<Array<db.AttendanceRecord>>;

export function ListClients(arg1:string,arg2:boolean):Promise<Array<db.Client>>;

export function ListIssues(arg1:string):Promise<Array<db.Issue>>;

export function ListMemberAssignments(arg1:string,arg2:string):Promise<Array<db.MemberAssignment>>;

export function ListMyWeeklyReports():Promise<Array<db.WeeklyReport>>;

export function ListRetrospectives():Promise<Array<db.Retrospective>>;

export function ListSIProjects():Promise<Array<db.ProjectWithClient>>;

export function ListTeamMembers():Promise<Array<db.TeamMember>>;

export function ListWeeklyReports():Promise<Array<db.WeeklyReport>>;

export function LookupLinearViewer(arg1:string):Promise<Record<string, string>>;

export function MiniMaxChatWithMessages(arg1:string,arg2:Array<main.OpenAIChatMessage>):Promise<main.OpenAIChatResult>;

export function OpenAIChatWithMessages(arg1:string,arg2:Array<main.OpenAIChatMessage>):Promise<main.OpenAIChatResult>;

export function OpenFile(arg1:string):Promise<void>;

export function PopulateReportFromLinear(arg1:number,arg2:string,arg3:string):Promise<number>;

export function PopulateReportFromProjects(arg1:number,arg2:string,arg3:string):Promise<number>;

export function PopulateReportFromTeamData(arg1:number):Promise<number>;

export function PreprocessReportItemsWithAI(arg1:number):Promise<main.SyncResult>;

export function RefineMarkdownWithAI(arg1:string):Promise<string>;

export function RefreshUSDKRWRate(arg1:string):Promise<db.AIFXRate>;

export function RefreshVault():Promise<number>;

export function RetrieveVaultContext(arg1:string,arg2:number):Promise<Array<db.VaultReference>>;

export function RunKnowledgeBaseLint():Promise<db.IngestResult>;

export function SaveAIBillingPlan(arg1:number,arg2:number,arg3:number,arg4:number,arg5:number,arg6:number,arg7:number,arg8:number,arg9:string,arg10:string):Promise<db.AIBillingPlan>;

export function SaveAIModel(arg1:number,arg2:number,arg3:string,arg4:string,arg5:boolean):Promise<db.AIModel>;

export function SaveAIProvider(arg1:number,arg2:string,arg3:string,arg4:boolean):Promise<db.AIProvider>;

export function SaveAttendanceRecord(arg1:db.AttendanceRecord):Promise<db.AttendanceRecord>;

export function SaveClient(arg1:db.Client):Promise<db.Client>;

export function SaveIntegration(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function SaveIssue(arg1:db.Issue):Promise<number>;

export function SaveKnowledgeQuery(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<string>):Promise<db.IngestResult>;

export function SaveMemberAssignment(arg1:db.MemberAssignment):Promise<db.MemberAssignment>;

export function SaveRetrospective(arg1:db.Retrospective):Promise<number>;

export function SaveSIProject(arg1:db.Project):Promise<db.Project>;

export function SaveSIProjectDetail(arg1:db.SIProjectDetail):Promise<db.SIProjectDetail>;

export function SaveSIProjectMember(arg1:db.SIProjectMember):Promise<db.SIProjectMember>;

export function SaveSIWeeklyReport(arg1:db.SIWeeklyReport):Promise<db.SIWeeklyReport>;

export function SaveTeamMember(arg1:db.TeamMember):Promise<db.TeamMember>;

export function ScanClaudeSkills():Promise<Array<main.SkillCommand>>;

export function SearchVault(arg1:string):Promise<Array<db.VaultItem>>;

export function SetPersonalAIAutoCollect(arg1:boolean,arg2:number):Promise<db.PersonalAIAutoCollectConfig>;

export function SetupGWSAuth():Promise<string>;

export function SetupTeamProfile(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function StartPersonalAIUsageCollection(arg1:string):Promise<db.PersonalAICollectStatus>;

export function SyncAll(arg1:string,arg2:string):Promise<Array<main.SyncResult>>;

export function SyncGmail(arg1:string,arg2:string):Promise<main.SyncResult>;

export function SyncGoogleCalendar(arg1:string,arg2:string):Promise<main.SyncResult>;

export function UpdateLinearIssue(arg1:string,arg2:main.LinearIssueUpdateInput):Promise<void>;

export function UpdateLinearIssueState(arg1:string,arg2:string):Promise<void>;

export function UpdateReportItem(arg1:db.ReportItem):Promise<void>;

export function UpdateSIProjectStatus(arg1:number,arg2:string):Promise<void>;

export function UpdateTeamProfile(arg1:db.TeamProfile):Promise<void>;

export function UpdateUser(arg1:string,arg2:string):Promise<void>;

export function UploadExcelTemplate():Promise<string>;

export function UploadExcelTemplateForType(arg1:string):Promise<string>;
